name: Docker Image for ddns app

on:
  push:
    branches: [ master ]
    paths:
      - 'cf-ddns/**'
      - '.github/workflows/cf-ddns-docker.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
        
      - name: 'Build and Push'
        uses: docker/build-push-action@v1
        with:
          path: cf-ddns
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mshade/cf-ddns
          tag_with_sha: true
          tag_with_ref: true
