name: Docker Image for kubernetes tools

on:
  push:
    branches: [ master ]
    paths:
      - 'kubetools/**'
      - '.github/workflows/kubetools-docker.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
        
      - name: 'Build and Push'
        uses: docker/build-push-action@v1
        with:
          path: kubetools
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mshade/kubetools
          tag_with_sha: true
          tag_with_ref: true

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: mshade/kubetools
          README_FILEPATH: ./kubetools/README.md
